// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: epoch.proto

#ifndef PROTOBUF_INCLUDED_epoch_2eproto
#define PROTOBUF_INCLUDED_epoch_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_epoch_2eproto 

namespace protobuf_epoch_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[5];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
}  // namespace protobuf_epoch_2eproto
namespace epoch {
class AddrAssoc;
class AddrAssocDefaultTypeInternal;
extern AddrAssocDefaultTypeInternal _AddrAssoc_default_instance_;
class ArpAssoc;
class ArpAssocDefaultTypeInternal;
extern ArpAssocDefaultTypeInternal _ArpAssoc_default_instance_;
class DeviceComm;
class DeviceCommDefaultTypeInternal;
extern DeviceCommDefaultTypeInternal _DeviceComm_default_instance_;
class EpochStep;
class EpochStepDefaultTypeInternal;
extern EpochStepDefaultTypeInternal _EpochStep_default_instance_;
class L2Summary;
class L2SummaryDefaultTypeInternal;
extern L2SummaryDefaultTypeInternal _L2Summary_default_instance_;
}  // namespace epoch
namespace google {
namespace protobuf {
template<> ::epoch::AddrAssoc* Arena::CreateMaybeMessage<::epoch::AddrAssoc>(Arena*);
template<> ::epoch::ArpAssoc* Arena::CreateMaybeMessage<::epoch::ArpAssoc>(Arena*);
template<> ::epoch::DeviceComm* Arena::CreateMaybeMessage<::epoch::DeviceComm>(Arena*);
template<> ::epoch::EpochStep* Arena::CreateMaybeMessage<::epoch::EpochStep>(Arena*);
template<> ::epoch::L2Summary* Arena::CreateMaybeMessage<::epoch::L2Summary>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace epoch {

// ===================================================================

class L2Summary : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:epoch.L2Summary) */ {
 public:
  L2Summary();
  virtual ~L2Summary();

  L2Summary(const L2Summary& from);

  inline L2Summary& operator=(const L2Summary& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  L2Summary(L2Summary&& from) noexcept
    : L2Summary() {
    *this = ::std::move(from);
  }

  inline L2Summary& operator=(L2Summary&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const L2Summary& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const L2Summary* internal_default_instance() {
    return reinterpret_cast<const L2Summary*>(
               &_L2Summary_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(L2Summary* other);
  friend void swap(L2Summary& a, L2Summary& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline L2Summary* New() const final {
    return CreateMaybeMessage<L2Summary>(NULL);
  }

  L2Summary* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<L2Summary>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const L2Summary& from);
  void MergeFrom(const L2Summary& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(L2Summary* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // fixed64 mac_dst = 1;
  void clear_mac_dst();
  static const int kMacDstFieldNumber = 1;
  ::google::protobuf::uint64 mac_dst() const;
  void set_mac_dst(::google::protobuf::uint64 value);

  // uint32 ipv4 = 2;
  void clear_ipv4();
  static const int kIpv4FieldNumber = 2;
  ::google::protobuf::uint32 ipv4() const;
  void set_ipv4(::google::protobuf::uint32 value);

  // uint32 ipv6 = 3;
  void clear_ipv6();
  static const int kIpv6FieldNumber = 3;
  ::google::protobuf::uint32 ipv6() const;
  void set_ipv6(::google::protobuf::uint32 value);

  // uint32 arp = 4;
  void clear_arp();
  static const int kArpFieldNumber = 4;
  ::google::protobuf::uint32 arp() const;
  void set_arp(::google::protobuf::uint32 value);

  // uint32 unknown = 5;
  void clear_unknown();
  static const int kUnknownFieldNumber = 5;
  ::google::protobuf::uint32 unknown() const;
  void set_unknown(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:epoch.L2Summary)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::uint64 mac_dst_;
  ::google::protobuf::uint32 ipv4_;
  ::google::protobuf::uint32 ipv6_;
  ::google::protobuf::uint32 arp_;
  ::google::protobuf::uint32 unknown_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_epoch_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class DeviceComm : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:epoch.DeviceComm) */ {
 public:
  DeviceComm();
  virtual ~DeviceComm();

  DeviceComm(const DeviceComm& from);

  inline DeviceComm& operator=(const DeviceComm& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DeviceComm(DeviceComm&& from) noexcept
    : DeviceComm() {
    *this = ::std::move(from);
  }

  inline DeviceComm& operator=(DeviceComm&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const DeviceComm& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DeviceComm* internal_default_instance() {
    return reinterpret_cast<const DeviceComm*>(
               &_DeviceComm_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(DeviceComm* other);
  friend void swap(DeviceComm& a, DeviceComm& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DeviceComm* New() const final {
    return CreateMaybeMessage<DeviceComm>(NULL);
  }

  DeviceComm* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<DeviceComm>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const DeviceComm& from);
  void MergeFrom(const DeviceComm& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DeviceComm* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .epoch.L2Summary tx_summary = 2;
  int tx_summary_size() const;
  void clear_tx_summary();
  static const int kTxSummaryFieldNumber = 2;
  ::epoch::L2Summary* mutable_tx_summary(int index);
  ::google::protobuf::RepeatedPtrField< ::epoch::L2Summary >*
      mutable_tx_summary();
  const ::epoch::L2Summary& tx_summary(int index) const;
  ::epoch::L2Summary* add_tx_summary();
  const ::google::protobuf::RepeatedPtrField< ::epoch::L2Summary >&
      tx_summary() const;

  // .epoch.L2Summary bcast_33 = 3;
  bool has_bcast_33() const;
  void clear_bcast_33();
  static const int kBcast33FieldNumber = 3;
  private:
  const ::epoch::L2Summary& _internal_bcast_33() const;
  public:
  const ::epoch::L2Summary& bcast_33() const;
  ::epoch::L2Summary* release_bcast_33();
  ::epoch::L2Summary* mutable_bcast_33();
  void set_allocated_bcast_33(::epoch::L2Summary* bcast_33);

  // .epoch.L2Summary bcast_ff = 4;
  bool has_bcast_ff() const;
  void clear_bcast_ff();
  static const int kBcastFfFieldNumber = 4;
  private:
  const ::epoch::L2Summary& _internal_bcast_ff() const;
  public:
  const ::epoch::L2Summary& bcast_ff() const;
  ::epoch::L2Summary* release_bcast_ff();
  ::epoch::L2Summary* mutable_bcast_ff();
  void set_allocated_bcast_ff(::epoch::L2Summary* bcast_ff);

  // .epoch.L2Summary bcast_01 = 5;
  bool has_bcast_01() const;
  void clear_bcast_01();
  static const int kBcast01FieldNumber = 5;
  private:
  const ::epoch::L2Summary& _internal_bcast_01() const;
  public:
  const ::epoch::L2Summary& bcast_01() const;
  ::epoch::L2Summary* release_bcast_01();
  ::epoch::L2Summary* mutable_bcast_01();
  void set_allocated_bcast_01(::epoch::L2Summary* bcast_01);

  // .epoch.L2Summary bcast_xx = 6;
  bool has_bcast_xx() const;
  void clear_bcast_xx();
  static const int kBcastXxFieldNumber = 6;
  private:
  const ::epoch::L2Summary& _internal_bcast_xx() const;
  public:
  const ::epoch::L2Summary& bcast_xx() const;
  ::epoch::L2Summary* release_bcast_xx();
  ::epoch::L2Summary* mutable_bcast_xx();
  void set_allocated_bcast_xx(::epoch::L2Summary* bcast_xx);

  // fixed64 mac_src = 1;
  void clear_mac_src();
  static const int kMacSrcFieldNumber = 1;
  ::google::protobuf::uint64 mac_src() const;
  void set_mac_src(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:epoch.DeviceComm)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::epoch::L2Summary > tx_summary_;
  ::epoch::L2Summary* bcast_33_;
  ::epoch::L2Summary* bcast_ff_;
  ::epoch::L2Summary* bcast_01_;
  ::epoch::L2Summary* bcast_xx_;
  ::google::protobuf::uint64 mac_src_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_epoch_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AddrAssoc : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:epoch.AddrAssoc) */ {
 public:
  AddrAssoc();
  virtual ~AddrAssoc();

  AddrAssoc(const AddrAssoc& from);

  inline AddrAssoc& operator=(const AddrAssoc& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AddrAssoc(AddrAssoc&& from) noexcept
    : AddrAssoc() {
    *this = ::std::move(from);
  }

  inline AddrAssoc& operator=(AddrAssoc&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const AddrAssoc& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AddrAssoc* internal_default_instance() {
    return reinterpret_cast<const AddrAssoc*>(
               &_AddrAssoc_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(AddrAssoc* other);
  friend void swap(AddrAssoc& a, AddrAssoc& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AddrAssoc* New() const final {
    return CreateMaybeMessage<AddrAssoc>(NULL);
  }

  AddrAssoc* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AddrAssoc>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const AddrAssoc& from);
  void MergeFrom(const AddrAssoc& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(AddrAssoc* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // fixed64 mac_src = 1;
  void clear_mac_src();
  static const int kMacSrcFieldNumber = 1;
  ::google::protobuf::uint64 mac_src() const;
  void set_mac_src(::google::protobuf::uint64 value);

  // fixed32 ipv4 = 2;
  void clear_ipv4();
  static const int kIpv4FieldNumber = 2;
  ::google::protobuf::uint32 ipv4() const;
  void set_ipv4(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:epoch.AddrAssoc)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::uint64 mac_src_;
  ::google::protobuf::uint32 ipv4_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_epoch_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ArpAssoc : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:epoch.ArpAssoc) */ {
 public:
  ArpAssoc();
  virtual ~ArpAssoc();

  ArpAssoc(const ArpAssoc& from);

  inline ArpAssoc& operator=(const ArpAssoc& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ArpAssoc(ArpAssoc&& from) noexcept
    : ArpAssoc() {
    *this = ::std::move(from);
  }

  inline ArpAssoc& operator=(ArpAssoc&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ArpAssoc& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ArpAssoc* internal_default_instance() {
    return reinterpret_cast<const ArpAssoc*>(
               &_ArpAssoc_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(ArpAssoc* other);
  friend void swap(ArpAssoc& a, ArpAssoc& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ArpAssoc* New() const final {
    return CreateMaybeMessage<ArpAssoc>(NULL);
  }

  ArpAssoc* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ArpAssoc>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const ArpAssoc& from);
  void MergeFrom(const ArpAssoc& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ArpAssoc* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .epoch.AddrAssoc table_row = 2;
  int table_row_size() const;
  void clear_table_row();
  static const int kTableRowFieldNumber = 2;
  ::epoch::AddrAssoc* mutable_table_row(int index);
  ::google::protobuf::RepeatedPtrField< ::epoch::AddrAssoc >*
      mutable_table_row();
  const ::epoch::AddrAssoc& table_row(int index) const;
  ::epoch::AddrAssoc* add_table_row();
  const ::google::protobuf::RepeatedPtrField< ::epoch::AddrAssoc >&
      table_row() const;

  // fixed64 mac_src = 1;
  void clear_mac_src();
  static const int kMacSrcFieldNumber = 1;
  ::google::protobuf::uint64 mac_src() const;
  void set_mac_src(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:epoch.ArpAssoc)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::epoch::AddrAssoc > table_row_;
  ::google::protobuf::uint64 mac_src_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_epoch_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class EpochStep : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:epoch.EpochStep) */ {
 public:
  EpochStep();
  virtual ~EpochStep();

  EpochStep(const EpochStep& from);

  inline EpochStep& operator=(const EpochStep& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  EpochStep(EpochStep&& from) noexcept
    : EpochStep() {
    *this = ::std::move(from);
  }

  inline EpochStep& operator=(EpochStep&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const EpochStep& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const EpochStep* internal_default_instance() {
    return reinterpret_cast<const EpochStep*>(
               &_EpochStep_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(EpochStep* other);
  friend void swap(EpochStep& a, EpochStep& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline EpochStep* New() const final {
    return CreateMaybeMessage<EpochStep>(NULL);
  }

  EpochStep* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<EpochStep>(arena);
  }
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    final;
  void CopyFrom(const EpochStep& from);
  void MergeFrom(const EpochStep& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  void DiscardUnknownFields();
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(EpochStep* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated fixed64 enter_l2devices = 1;
  int enter_l2devices_size() const;
  void clear_enter_l2devices();
  static const int kEnterL2DevicesFieldNumber = 1;
  ::google::protobuf::uint64 enter_l2devices(int index) const;
  void set_enter_l2devices(int index, ::google::protobuf::uint64 value);
  void add_enter_l2devices(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      enter_l2devices() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_enter_l2devices();

  // repeated .epoch.DeviceComm l2_dev_comm = 2;
  int l2_dev_comm_size() const;
  void clear_l2_dev_comm();
  static const int kL2DevCommFieldNumber = 2;
  ::epoch::DeviceComm* mutable_l2_dev_comm(int index);
  ::google::protobuf::RepeatedPtrField< ::epoch::DeviceComm >*
      mutable_l2_dev_comm();
  const ::epoch::DeviceComm& l2_dev_comm(int index) const;
  ::epoch::DeviceComm* add_l2_dev_comm();
  const ::google::protobuf::RepeatedPtrField< ::epoch::DeviceComm >&
      l2_dev_comm() const;

  // repeated .epoch.AddrAssoc enter_l2_ipv4_addr_src = 3;
  int enter_l2_ipv4_addr_src_size() const;
  void clear_enter_l2_ipv4_addr_src();
  static const int kEnterL2Ipv4AddrSrcFieldNumber = 3;
  ::epoch::AddrAssoc* mutable_enter_l2_ipv4_addr_src(int index);
  ::google::protobuf::RepeatedPtrField< ::epoch::AddrAssoc >*
      mutable_enter_l2_ipv4_addr_src();
  const ::epoch::AddrAssoc& enter_l2_ipv4_addr_src(int index) const;
  ::epoch::AddrAssoc* add_enter_l2_ipv4_addr_src();
  const ::google::protobuf::RepeatedPtrField< ::epoch::AddrAssoc >&
      enter_l2_ipv4_addr_src() const;

  // repeated .epoch.ArpAssoc enter_arp_table = 4;
  int enter_arp_table_size() const;
  void clear_enter_arp_table();
  static const int kEnterArpTableFieldNumber = 4;
  ::epoch::ArpAssoc* mutable_enter_arp_table(int index);
  ::google::protobuf::RepeatedPtrField< ::epoch::ArpAssoc >*
      mutable_enter_arp_table();
  const ::epoch::ArpAssoc& enter_arp_table(int index) const;
  ::epoch::ArpAssoc* add_enter_arp_table();
  const ::google::protobuf::RepeatedPtrField< ::epoch::ArpAssoc >&
      enter_arp_table() const;

  // @@protoc_insertion_point(class_scope:epoch.EpochStep)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > enter_l2devices_;
  mutable int _enter_l2devices_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField< ::epoch::DeviceComm > l2_dev_comm_;
  ::google::protobuf::RepeatedPtrField< ::epoch::AddrAssoc > enter_l2_ipv4_addr_src_;
  ::google::protobuf::RepeatedPtrField< ::epoch::ArpAssoc > enter_arp_table_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_epoch_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// L2Summary

// fixed64 mac_dst = 1;
inline void L2Summary::clear_mac_dst() {
  mac_dst_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 L2Summary::mac_dst() const {
  // @@protoc_insertion_point(field_get:epoch.L2Summary.mac_dst)
  return mac_dst_;
}
inline void L2Summary::set_mac_dst(::google::protobuf::uint64 value) {
  
  mac_dst_ = value;
  // @@protoc_insertion_point(field_set:epoch.L2Summary.mac_dst)
}

// uint32 ipv4 = 2;
inline void L2Summary::clear_ipv4() {
  ipv4_ = 0u;
}
inline ::google::protobuf::uint32 L2Summary::ipv4() const {
  // @@protoc_insertion_point(field_get:epoch.L2Summary.ipv4)
  return ipv4_;
}
inline void L2Summary::set_ipv4(::google::protobuf::uint32 value) {
  
  ipv4_ = value;
  // @@protoc_insertion_point(field_set:epoch.L2Summary.ipv4)
}

// uint32 ipv6 = 3;
inline void L2Summary::clear_ipv6() {
  ipv6_ = 0u;
}
inline ::google::protobuf::uint32 L2Summary::ipv6() const {
  // @@protoc_insertion_point(field_get:epoch.L2Summary.ipv6)
  return ipv6_;
}
inline void L2Summary::set_ipv6(::google::protobuf::uint32 value) {
  
  ipv6_ = value;
  // @@protoc_insertion_point(field_set:epoch.L2Summary.ipv6)
}

// uint32 arp = 4;
inline void L2Summary::clear_arp() {
  arp_ = 0u;
}
inline ::google::protobuf::uint32 L2Summary::arp() const {
  // @@protoc_insertion_point(field_get:epoch.L2Summary.arp)
  return arp_;
}
inline void L2Summary::set_arp(::google::protobuf::uint32 value) {
  
  arp_ = value;
  // @@protoc_insertion_point(field_set:epoch.L2Summary.arp)
}

// uint32 unknown = 5;
inline void L2Summary::clear_unknown() {
  unknown_ = 0u;
}
inline ::google::protobuf::uint32 L2Summary::unknown() const {
  // @@protoc_insertion_point(field_get:epoch.L2Summary.unknown)
  return unknown_;
}
inline void L2Summary::set_unknown(::google::protobuf::uint32 value) {
  
  unknown_ = value;
  // @@protoc_insertion_point(field_set:epoch.L2Summary.unknown)
}

// -------------------------------------------------------------------

// DeviceComm

// fixed64 mac_src = 1;
inline void DeviceComm::clear_mac_src() {
  mac_src_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 DeviceComm::mac_src() const {
  // @@protoc_insertion_point(field_get:epoch.DeviceComm.mac_src)
  return mac_src_;
}
inline void DeviceComm::set_mac_src(::google::protobuf::uint64 value) {
  
  mac_src_ = value;
  // @@protoc_insertion_point(field_set:epoch.DeviceComm.mac_src)
}

// repeated .epoch.L2Summary tx_summary = 2;
inline int DeviceComm::tx_summary_size() const {
  return tx_summary_.size();
}
inline void DeviceComm::clear_tx_summary() {
  tx_summary_.Clear();
}
inline ::epoch::L2Summary* DeviceComm::mutable_tx_summary(int index) {
  // @@protoc_insertion_point(field_mutable:epoch.DeviceComm.tx_summary)
  return tx_summary_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::epoch::L2Summary >*
DeviceComm::mutable_tx_summary() {
  // @@protoc_insertion_point(field_mutable_list:epoch.DeviceComm.tx_summary)
  return &tx_summary_;
}
inline const ::epoch::L2Summary& DeviceComm::tx_summary(int index) const {
  // @@protoc_insertion_point(field_get:epoch.DeviceComm.tx_summary)
  return tx_summary_.Get(index);
}
inline ::epoch::L2Summary* DeviceComm::add_tx_summary() {
  // @@protoc_insertion_point(field_add:epoch.DeviceComm.tx_summary)
  return tx_summary_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::epoch::L2Summary >&
DeviceComm::tx_summary() const {
  // @@protoc_insertion_point(field_list:epoch.DeviceComm.tx_summary)
  return tx_summary_;
}

// .epoch.L2Summary bcast_33 = 3;
inline bool DeviceComm::has_bcast_33() const {
  return this != internal_default_instance() && bcast_33_ != NULL;
}
inline void DeviceComm::clear_bcast_33() {
  if (GetArenaNoVirtual() == NULL && bcast_33_ != NULL) {
    delete bcast_33_;
  }
  bcast_33_ = NULL;
}
inline const ::epoch::L2Summary& DeviceComm::_internal_bcast_33() const {
  return *bcast_33_;
}
inline const ::epoch::L2Summary& DeviceComm::bcast_33() const {
  const ::epoch::L2Summary* p = bcast_33_;
  // @@protoc_insertion_point(field_get:epoch.DeviceComm.bcast_33)
  return p != NULL ? *p : *reinterpret_cast<const ::epoch::L2Summary*>(
      &::epoch::_L2Summary_default_instance_);
}
inline ::epoch::L2Summary* DeviceComm::release_bcast_33() {
  // @@protoc_insertion_point(field_release:epoch.DeviceComm.bcast_33)
  
  ::epoch::L2Summary* temp = bcast_33_;
  bcast_33_ = NULL;
  return temp;
}
inline ::epoch::L2Summary* DeviceComm::mutable_bcast_33() {
  
  if (bcast_33_ == NULL) {
    auto* p = CreateMaybeMessage<::epoch::L2Summary>(GetArenaNoVirtual());
    bcast_33_ = p;
  }
  // @@protoc_insertion_point(field_mutable:epoch.DeviceComm.bcast_33)
  return bcast_33_;
}
inline void DeviceComm::set_allocated_bcast_33(::epoch::L2Summary* bcast_33) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete bcast_33_;
  }
  if (bcast_33) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      bcast_33 = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, bcast_33, submessage_arena);
    }
    
  } else {
    
  }
  bcast_33_ = bcast_33;
  // @@protoc_insertion_point(field_set_allocated:epoch.DeviceComm.bcast_33)
}

// .epoch.L2Summary bcast_ff = 4;
inline bool DeviceComm::has_bcast_ff() const {
  return this != internal_default_instance() && bcast_ff_ != NULL;
}
inline void DeviceComm::clear_bcast_ff() {
  if (GetArenaNoVirtual() == NULL && bcast_ff_ != NULL) {
    delete bcast_ff_;
  }
  bcast_ff_ = NULL;
}
inline const ::epoch::L2Summary& DeviceComm::_internal_bcast_ff() const {
  return *bcast_ff_;
}
inline const ::epoch::L2Summary& DeviceComm::bcast_ff() const {
  const ::epoch::L2Summary* p = bcast_ff_;
  // @@protoc_insertion_point(field_get:epoch.DeviceComm.bcast_ff)
  return p != NULL ? *p : *reinterpret_cast<const ::epoch::L2Summary*>(
      &::epoch::_L2Summary_default_instance_);
}
inline ::epoch::L2Summary* DeviceComm::release_bcast_ff() {
  // @@protoc_insertion_point(field_release:epoch.DeviceComm.bcast_ff)
  
  ::epoch::L2Summary* temp = bcast_ff_;
  bcast_ff_ = NULL;
  return temp;
}
inline ::epoch::L2Summary* DeviceComm::mutable_bcast_ff() {
  
  if (bcast_ff_ == NULL) {
    auto* p = CreateMaybeMessage<::epoch::L2Summary>(GetArenaNoVirtual());
    bcast_ff_ = p;
  }
  // @@protoc_insertion_point(field_mutable:epoch.DeviceComm.bcast_ff)
  return bcast_ff_;
}
inline void DeviceComm::set_allocated_bcast_ff(::epoch::L2Summary* bcast_ff) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete bcast_ff_;
  }
  if (bcast_ff) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      bcast_ff = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, bcast_ff, submessage_arena);
    }
    
  } else {
    
  }
  bcast_ff_ = bcast_ff;
  // @@protoc_insertion_point(field_set_allocated:epoch.DeviceComm.bcast_ff)
}

// .epoch.L2Summary bcast_01 = 5;
inline bool DeviceComm::has_bcast_01() const {
  return this != internal_default_instance() && bcast_01_ != NULL;
}
inline void DeviceComm::clear_bcast_01() {
  if (GetArenaNoVirtual() == NULL && bcast_01_ != NULL) {
    delete bcast_01_;
  }
  bcast_01_ = NULL;
}
inline const ::epoch::L2Summary& DeviceComm::_internal_bcast_01() const {
  return *bcast_01_;
}
inline const ::epoch::L2Summary& DeviceComm::bcast_01() const {
  const ::epoch::L2Summary* p = bcast_01_;
  // @@protoc_insertion_point(field_get:epoch.DeviceComm.bcast_01)
  return p != NULL ? *p : *reinterpret_cast<const ::epoch::L2Summary*>(
      &::epoch::_L2Summary_default_instance_);
}
inline ::epoch::L2Summary* DeviceComm::release_bcast_01() {
  // @@protoc_insertion_point(field_release:epoch.DeviceComm.bcast_01)
  
  ::epoch::L2Summary* temp = bcast_01_;
  bcast_01_ = NULL;
  return temp;
}
inline ::epoch::L2Summary* DeviceComm::mutable_bcast_01() {
  
  if (bcast_01_ == NULL) {
    auto* p = CreateMaybeMessage<::epoch::L2Summary>(GetArenaNoVirtual());
    bcast_01_ = p;
  }
  // @@protoc_insertion_point(field_mutable:epoch.DeviceComm.bcast_01)
  return bcast_01_;
}
inline void DeviceComm::set_allocated_bcast_01(::epoch::L2Summary* bcast_01) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete bcast_01_;
  }
  if (bcast_01) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      bcast_01 = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, bcast_01, submessage_arena);
    }
    
  } else {
    
  }
  bcast_01_ = bcast_01;
  // @@protoc_insertion_point(field_set_allocated:epoch.DeviceComm.bcast_01)
}

// .epoch.L2Summary bcast_xx = 6;
inline bool DeviceComm::has_bcast_xx() const {
  return this != internal_default_instance() && bcast_xx_ != NULL;
}
inline void DeviceComm::clear_bcast_xx() {
  if (GetArenaNoVirtual() == NULL && bcast_xx_ != NULL) {
    delete bcast_xx_;
  }
  bcast_xx_ = NULL;
}
inline const ::epoch::L2Summary& DeviceComm::_internal_bcast_xx() const {
  return *bcast_xx_;
}
inline const ::epoch::L2Summary& DeviceComm::bcast_xx() const {
  const ::epoch::L2Summary* p = bcast_xx_;
  // @@protoc_insertion_point(field_get:epoch.DeviceComm.bcast_xx)
  return p != NULL ? *p : *reinterpret_cast<const ::epoch::L2Summary*>(
      &::epoch::_L2Summary_default_instance_);
}
inline ::epoch::L2Summary* DeviceComm::release_bcast_xx() {
  // @@protoc_insertion_point(field_release:epoch.DeviceComm.bcast_xx)
  
  ::epoch::L2Summary* temp = bcast_xx_;
  bcast_xx_ = NULL;
  return temp;
}
inline ::epoch::L2Summary* DeviceComm::mutable_bcast_xx() {
  
  if (bcast_xx_ == NULL) {
    auto* p = CreateMaybeMessage<::epoch::L2Summary>(GetArenaNoVirtual());
    bcast_xx_ = p;
  }
  // @@protoc_insertion_point(field_mutable:epoch.DeviceComm.bcast_xx)
  return bcast_xx_;
}
inline void DeviceComm::set_allocated_bcast_xx(::epoch::L2Summary* bcast_xx) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete bcast_xx_;
  }
  if (bcast_xx) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      bcast_xx = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, bcast_xx, submessage_arena);
    }
    
  } else {
    
  }
  bcast_xx_ = bcast_xx;
  // @@protoc_insertion_point(field_set_allocated:epoch.DeviceComm.bcast_xx)
}

// -------------------------------------------------------------------

// AddrAssoc

// fixed64 mac_src = 1;
inline void AddrAssoc::clear_mac_src() {
  mac_src_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 AddrAssoc::mac_src() const {
  // @@protoc_insertion_point(field_get:epoch.AddrAssoc.mac_src)
  return mac_src_;
}
inline void AddrAssoc::set_mac_src(::google::protobuf::uint64 value) {
  
  mac_src_ = value;
  // @@protoc_insertion_point(field_set:epoch.AddrAssoc.mac_src)
}

// fixed32 ipv4 = 2;
inline void AddrAssoc::clear_ipv4() {
  ipv4_ = 0u;
}
inline ::google::protobuf::uint32 AddrAssoc::ipv4() const {
  // @@protoc_insertion_point(field_get:epoch.AddrAssoc.ipv4)
  return ipv4_;
}
inline void AddrAssoc::set_ipv4(::google::protobuf::uint32 value) {
  
  ipv4_ = value;
  // @@protoc_insertion_point(field_set:epoch.AddrAssoc.ipv4)
}

// -------------------------------------------------------------------

// ArpAssoc

// fixed64 mac_src = 1;
inline void ArpAssoc::clear_mac_src() {
  mac_src_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ArpAssoc::mac_src() const {
  // @@protoc_insertion_point(field_get:epoch.ArpAssoc.mac_src)
  return mac_src_;
}
inline void ArpAssoc::set_mac_src(::google::protobuf::uint64 value) {
  
  mac_src_ = value;
  // @@protoc_insertion_point(field_set:epoch.ArpAssoc.mac_src)
}

// repeated .epoch.AddrAssoc table_row = 2;
inline int ArpAssoc::table_row_size() const {
  return table_row_.size();
}
inline void ArpAssoc::clear_table_row() {
  table_row_.Clear();
}
inline ::epoch::AddrAssoc* ArpAssoc::mutable_table_row(int index) {
  // @@protoc_insertion_point(field_mutable:epoch.ArpAssoc.table_row)
  return table_row_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::epoch::AddrAssoc >*
ArpAssoc::mutable_table_row() {
  // @@protoc_insertion_point(field_mutable_list:epoch.ArpAssoc.table_row)
  return &table_row_;
}
inline const ::epoch::AddrAssoc& ArpAssoc::table_row(int index) const {
  // @@protoc_insertion_point(field_get:epoch.ArpAssoc.table_row)
  return table_row_.Get(index);
}
inline ::epoch::AddrAssoc* ArpAssoc::add_table_row() {
  // @@protoc_insertion_point(field_add:epoch.ArpAssoc.table_row)
  return table_row_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::epoch::AddrAssoc >&
ArpAssoc::table_row() const {
  // @@protoc_insertion_point(field_list:epoch.ArpAssoc.table_row)
  return table_row_;
}

// -------------------------------------------------------------------

// EpochStep

// repeated fixed64 enter_l2devices = 1;
inline int EpochStep::enter_l2devices_size() const {
  return enter_l2devices_.size();
}
inline void EpochStep::clear_enter_l2devices() {
  enter_l2devices_.Clear();
}
inline ::google::protobuf::uint64 EpochStep::enter_l2devices(int index) const {
  // @@protoc_insertion_point(field_get:epoch.EpochStep.enter_l2devices)
  return enter_l2devices_.Get(index);
}
inline void EpochStep::set_enter_l2devices(int index, ::google::protobuf::uint64 value) {
  enter_l2devices_.Set(index, value);
  // @@protoc_insertion_point(field_set:epoch.EpochStep.enter_l2devices)
}
inline void EpochStep::add_enter_l2devices(::google::protobuf::uint64 value) {
  enter_l2devices_.Add(value);
  // @@protoc_insertion_point(field_add:epoch.EpochStep.enter_l2devices)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
EpochStep::enter_l2devices() const {
  // @@protoc_insertion_point(field_list:epoch.EpochStep.enter_l2devices)
  return enter_l2devices_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
EpochStep::mutable_enter_l2devices() {
  // @@protoc_insertion_point(field_mutable_list:epoch.EpochStep.enter_l2devices)
  return &enter_l2devices_;
}

// repeated .epoch.DeviceComm l2_dev_comm = 2;
inline int EpochStep::l2_dev_comm_size() const {
  return l2_dev_comm_.size();
}
inline void EpochStep::clear_l2_dev_comm() {
  l2_dev_comm_.Clear();
}
inline ::epoch::DeviceComm* EpochStep::mutable_l2_dev_comm(int index) {
  // @@protoc_insertion_point(field_mutable:epoch.EpochStep.l2_dev_comm)
  return l2_dev_comm_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::epoch::DeviceComm >*
EpochStep::mutable_l2_dev_comm() {
  // @@protoc_insertion_point(field_mutable_list:epoch.EpochStep.l2_dev_comm)
  return &l2_dev_comm_;
}
inline const ::epoch::DeviceComm& EpochStep::l2_dev_comm(int index) const {
  // @@protoc_insertion_point(field_get:epoch.EpochStep.l2_dev_comm)
  return l2_dev_comm_.Get(index);
}
inline ::epoch::DeviceComm* EpochStep::add_l2_dev_comm() {
  // @@protoc_insertion_point(field_add:epoch.EpochStep.l2_dev_comm)
  return l2_dev_comm_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::epoch::DeviceComm >&
EpochStep::l2_dev_comm() const {
  // @@protoc_insertion_point(field_list:epoch.EpochStep.l2_dev_comm)
  return l2_dev_comm_;
}

// repeated .epoch.AddrAssoc enter_l2_ipv4_addr_src = 3;
inline int EpochStep::enter_l2_ipv4_addr_src_size() const {
  return enter_l2_ipv4_addr_src_.size();
}
inline void EpochStep::clear_enter_l2_ipv4_addr_src() {
  enter_l2_ipv4_addr_src_.Clear();
}
inline ::epoch::AddrAssoc* EpochStep::mutable_enter_l2_ipv4_addr_src(int index) {
  // @@protoc_insertion_point(field_mutable:epoch.EpochStep.enter_l2_ipv4_addr_src)
  return enter_l2_ipv4_addr_src_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::epoch::AddrAssoc >*
EpochStep::mutable_enter_l2_ipv4_addr_src() {
  // @@protoc_insertion_point(field_mutable_list:epoch.EpochStep.enter_l2_ipv4_addr_src)
  return &enter_l2_ipv4_addr_src_;
}
inline const ::epoch::AddrAssoc& EpochStep::enter_l2_ipv4_addr_src(int index) const {
  // @@protoc_insertion_point(field_get:epoch.EpochStep.enter_l2_ipv4_addr_src)
  return enter_l2_ipv4_addr_src_.Get(index);
}
inline ::epoch::AddrAssoc* EpochStep::add_enter_l2_ipv4_addr_src() {
  // @@protoc_insertion_point(field_add:epoch.EpochStep.enter_l2_ipv4_addr_src)
  return enter_l2_ipv4_addr_src_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::epoch::AddrAssoc >&
EpochStep::enter_l2_ipv4_addr_src() const {
  // @@protoc_insertion_point(field_list:epoch.EpochStep.enter_l2_ipv4_addr_src)
  return enter_l2_ipv4_addr_src_;
}

// repeated .epoch.ArpAssoc enter_arp_table = 4;
inline int EpochStep::enter_arp_table_size() const {
  return enter_arp_table_.size();
}
inline void EpochStep::clear_enter_arp_table() {
  enter_arp_table_.Clear();
}
inline ::epoch::ArpAssoc* EpochStep::mutable_enter_arp_table(int index) {
  // @@protoc_insertion_point(field_mutable:epoch.EpochStep.enter_arp_table)
  return enter_arp_table_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::epoch::ArpAssoc >*
EpochStep::mutable_enter_arp_table() {
  // @@protoc_insertion_point(field_mutable_list:epoch.EpochStep.enter_arp_table)
  return &enter_arp_table_;
}
inline const ::epoch::ArpAssoc& EpochStep::enter_arp_table(int index) const {
  // @@protoc_insertion_point(field_get:epoch.EpochStep.enter_arp_table)
  return enter_arp_table_.Get(index);
}
inline ::epoch::ArpAssoc* EpochStep::add_enter_arp_table() {
  // @@protoc_insertion_point(field_add:epoch.EpochStep.enter_arp_table)
  return enter_arp_table_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::epoch::ArpAssoc >&
EpochStep::enter_arp_table() const {
  // @@protoc_insertion_point(field_list:epoch.EpochStep.enter_arp_table)
  return enter_arp_table_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace epoch

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_epoch_2eproto
